INSERT INTO filial (name_filial, arcf) VALUES ('ОАО «Брагина, Одинцов и Федоров»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Лыткин Групп', True);
INSERT INTO filial (name_filial, arcf) VALUES ('ИП «Пономарева, Константинова и Дьячкова»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Матвеев и партнеры', True);
INSERT INTO filial (name_filial, arcf) VALUES ('ЗАО «Ефремова»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Кудряшова Лтд', True);
INSERT INTO filial (name_filial, arcf) VALUES ('РАО «Трофимова-Куликов»', False);
INSERT INTO filial (name_filial, arcf) VALUES ('НПО «Баранова-Медведев»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('ИП «Николаева, Антонова и Якушева»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Пестов Групп', False);
INSERT INTO filial (name_filial, arcf) VALUES ('РАО «Калашникова-Самойлова»', False);
INSERT INTO filial (name_filial, arcf) VALUES ('РАО «Суворова»', False);
INSERT INTO filial (name_filial, arcf) VALUES ('ЛУКОЙЛ', False);
INSERT INTO filial (name_filial, arcf) VALUES ('ОАО «Мишина, Харитонов и Мартынов»', False);
INSERT INTO filial (name_filial, arcf) VALUES ('ООО «Фадеева-Гусев»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Зуев Инкорпорэйтед', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Самсонов Инк', True);
INSERT INTO filial (name_filial, arcf) VALUES ('ЗАО «Белозерова-Смирнова»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('ЗАО «Логинов-Кудряшова»', True);
INSERT INTO filial (name_filial, arcf) VALUES ('Харитонов Лтд', True);
